name: Build project

on: [push]

jobs:
    build-android:
        name: Build android
        runs-on: self-hosted
        steps:
            - uses: game-ci/unity-builder@v4.1.3
              with:
                  targetPlatform: Android