name: Unity Build

on: [push]
    
jobs:
    build:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Build the Unity project
              run: |
                  /Applications/Unity/Hub/Editor/2021.3.16f1/Unity.app/Contents/MacOS/Unity -quit -batchmode -buildTarget android -executeMethod Code.CustomBuilder.AndroidDevelopment -projectPath /Users/ilakocura/ability-learning

            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Game-Build
                  path: /Users/BuildCi/testBuild.apk
