name: Build project

on: [push]

jobs:
  build-android:
    name: Build android
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          lfs: true
    