- name: Unity - Builder
  # You may pin to the exact commit or the version.
  # uses: game-ci/unity-builder@ff23166e3002a9f3f869621650dc992e657e17ce
  uses: game-ci/unity-builder@v4.1.3
  with:
    # Platform that the build should target.
    targetPlatform: # default is 
    # Version of unity to use for building the project. Use "auto" to get from your ProjectSettings/ProjectVersion.txt
    
