name: Build project

on: [push]

jobs:
  build-android:
    name: Build android
    runs-on: self-hosted
    steps:
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: Android
      - uses: actions/cache@v3
        with:
          path: /Users/ilakocura/ability-learning